### ISSUE TITLE
Any idea what these warnings are about?

### ISSUE THREAD

**Issue by IzzySoft** [ThirtyDegreesRay/OpenHub#1]
I've just sent the `.apk` through the scanners, and [VT reported some findings](https://www.virustotal.com/file/3842b2e5fa53a501d1ee42c9721991136d994be4622a1c67efa351faa4882c44/analysis/1505335327/). Any idea what that's about?

**Comment by ThirtyDegreesRay** [comment]
I don't think there are any virus in my apk.

**Comment by moriel5** [comment]
Don't worry, we don't think that you had put any malicious code yourself, it is probably a false alarm.

However, I would recommend checking the libraries that you use, there have been too many cases that apps contained malware, only because of certain libraries bgetting infected.

All that aside, I am looking forward to the day that I'll start using OpenHub full-time (currently I use ForkHub).

**Comment by ThirtyDegreesRay** [comment]
I have already checked the libraries and the file "classes15.dex", libraries seems no problem, the file "classes15.dex" is the code of android support v4, as you say, it is probably a false alarm.

Thanks for your support to OpenHub, I will always improve OpenHub.

**Comment by moriel5** [comment]
Even thus, it could scare potential users, so I'll scan the versions in Virus Total until it shows up clean by all of the engines.
Interestingly, the latest version shows that "classes15.dex", but flags the "classes16.dex" file.

If we would take the assumption that there is malware, perhaps there may be something in the buildchain, or with somwthing unrelated on your PC?

I am only trying to help OpenHub's growth and popularity, I am not saying that this is definite.

On another subject, what do you think of getting OpenHub into F-Droid?

**Comment by ThirtyDegreesRay** [comment]
I will check my project carefully on the weekend, I am curious about the cause.

About getting OpenHub into F-Droid, it's a good idea,  it's included in the plan now.

**Comment by moriel5** [comment]
That's great to hear, I can't wait to see OpenHub's growth by then.

And I haven't worked at all on the translation for the past three days, due to holidays, however I am back now (I don't touch any computers during my nation's holidays.

**Comment by ThirtyDegreesRay** [comment]
I disable the [android support multidex](https://developer.android.com/reference/android/support/multidex/MultiDex.html) in my project, the warning is gone([VT check result](https://www.virustotal.com/file/181915e062e24a475f0ad0db574ac6e7d6a0777e13800ac95ae1c9511d0e1188/analysis/1506304553/)).

So I think some dex files was suspicious on VT, but it's harmless actually.

OK, I come back from holidays, too.

**Comment by moriel5** [comment]
Happily, I can verify this in version 1.2.0.
The hebrew translation will take some time, as I am having trouble translating a few lines, however I am mostly finished.

**Comment by ThirtyDegreesRay** [comment]
Aha, enjoyed it.

**Comment by IzzySoft** [comment]
Thanks a lot for all your effort – glad to see the issue solved! And as @moriel5 correctly pointed out, we did not suspect "intentional malware" but wanted to make sure nobody is scared away and there's no "bad egg" in some library you wasn't aware of.

PS: Sorry for my delayed reply, I was on vacation and just returned today.

**Comment by ThirtyDegreesRay** [comment]
That's ok, thanks for your attention.

 OpenHub is developed by passion, I am try to make it better.
