### ISSUE TITLE
Add a Pure Black Theme

### ISSUE THREAD

**Issue by QIEXXII** [ThirtyDegreesRay/OpenHub#11]
The Dark Theme is pretty good.Would you please add a pure black theme?

Cause the pure black theme perfoms better on OLED devices.

**Comment by ThirtyDegreesRay** [comment]
I already know what you mean, but I don't have OLED devices, so I will try some way to perfoms better on OLED devices, but I can't see it directly, cloud you tell me the perfoms on OLED devices when pure black theme added.
