### ISSUE TITLE
theme reference which project or library?

### ISSUE THREAD

**Issue by yovenny** [ThirtyDegreesRay/OpenHub#142]
主题参考了那个项目或者库？，望解答

**Comment by yovenny** [comment]
![image](https://user-images.githubusercontent.com/8280857/41831850-f4501fb8-787b-11e8-8954-d401e543b235.png)

**Comment by pzhlkj6612** [comment]
https://github.com/ThirtyDegreesRay/OpenHub/blob/feff8b7c8c04a683abbf06228bf160b0638c6118/README.md#license
> Kosh(There are 13 files has some code copied from FastHub)

[FastHub](https://github.com/k0shk0sh/FastHub)
