### ISSUE TITLE
miui商店签名问题

### ISSUE THREAD

**Issue by Forty-nine** [ThirtyDegreesRay/OpenHub#153]
miui提示我，OpenHub在小米应用商店上的签名和Google play上的签名不同。
作者有在小米应用商店发布吗

**Comment by ThirtyDegreesRay** [comment]
在小米上发布过，的确有这个问题，Google paly上的签名和其他应用市场的不一样，是由于上传Google play时无意中勾选了Google签名计划，导致apk被Google重新签名了，还无法取消，所以只能这样了
