### ISSUE TITLE
主页不应该是News

### ISSUE THREAD

**Issue by DanteAndroid** [ThirtyDegreesRay/OpenHub#16]
建议与github保持一致，标题应该是activity（活动）才对

**Comment by ThirtyDegreesRay** [comment]
好的，我来统一下

**Comment by ThirtyDegreesRay** [comment]
纵观各个GitHub APP，命名有News、News Feed、Feeds，标题叫activity放在主界面有点不容易让人看懂。

**Comment by pzhlkj6612** [comment]
GitHub主页，那整个的大框叫`news column two-thirds`，然后有“Browse activity”和“Discover repositories”两部分。名叫“News”，却不含“Discover repositories”；名叫“Activity”，相比之下可能真的会好一些呢，毕竟如果某用户一开始就没用过网页版GitHub，那么他也应该不太能玩得转这个App。

**Comment by ThirtyDegreesRay** [comment]
@pzhlkj6612 @DanteAndroid 仔细想想，你们说的有理，和github网页端保持一致，使用“Activity”。
