### ISSUE TITLE
Maybe release this app to F-Droid?

### ISSUE THREAD

**Issue by genelocated** [ThirtyDegreesRay/OpenHub#167]
[F-Droid](https://f-droid.org) is a installable catelogue of *Free-and-Open-Source-Software* for Android.  
[F-Droid](https://f-droid.org) 是一个自由软件的安卓应用商店。

To get this app included, open an issue [here](https://gitlab.com/fdroid/rfp) (a GitLab account is required for that).  
要在 F-Droid 上上架这个应用，在 [这里](https://gitlab.com/fdroid/rfp) 提交一个 issue 就可以了。

**Comment by c-e-p-x-u-o** [comment]
related F-Droid issue https://gitlab.com/fdroid/rfp/issues/382
