### ISSUE TITLE
Releases时间错误

### ISSUE THREAD

**Issue by zwypfdsj** [ThirtyDegreesRay/OpenHub#17]
![图片1](https://i.loli.net/2017/12/15/5a3376b5aeb30.jpg)

![图片2](https://i.loli.net/2017/12/15/5a3376b5b5286.jpg)

**Comment by ThirtyDegreesRay** [comment]
检查了下，软件里使用的release的创建时间，github网页使用的release的发布时间，我来调整下。

**Comment by zwypfdsj** [comment]
好的，也就是说创建这个tag的时间并不是发布的时间？

**Comment by ThirtyDegreesRay** [comment]
可以先创建保存成草稿，之后再发布
