### ISSUE TITLE
更人性化地显示 size

### ISSUE THREAD

**Issue by June-6th** [ThirtyDegreesRay/OpenHub#195]
在一些项目中，size 没有以更合理的单位显示。

![错误的 size](https://user-images.githubusercontent.com/27896704/48603767-8636f800-e9b2-11e8-9f31-5a81cc688047.png)

**Comment by ThirtyDegreesRay** [comment]
@June-6th 问题收到了，今天就会发布新版修复
@XF-zhjnc 谢谢查找问题并修改
