### ISSUE TITLE
kuan gay hello , this app has a Notifications?

### ISSUE THREAD

**Issue by buzai** [ThirtyDegreesRay/OpenHub#2]

**Comment by ThirtyDegreesRay** [comment]
No notifications now.

**Comment by buzai** [comment]
@ThirtyDegreesRay thank u ,this app is so cool

**Comment by ThirtyDegreesRay** [comment]
谢谢支持，刚发现，我们明明可以用中文对话，O(∩_∩)O哈哈~

**Comment by buzai** [comment]
哈哈，似的，我不熟悉java，你是在app里做的auth认证拿得token吧，要想实现通知就得维护服务器里的token还得定时刷新任务

**Comment by ThirtyDegreesRay** [comment]
是用的OAuth认证，拿到token存在本地的，GitHub的API中也有获取通知消息，后台定时查询即可。 现在软件的功能还不完善，一步步做。
这是GitHub的API，感兴趣的话可以看看：https://developer.github.com/v3/

**Comment by buzai** [comment]
有包装好的api直接用就行
