### ISSUE TITLE
希望可以过滤指定语言的版本库

### ISSUE THREAD

**Issue by Vixb1122** [ThirtyDegreesRay/OpenHub#20]

**Comment by ThirtyDegreesRay** [comment]
对于搜索结果中显示的版本库，以后会加语言筛选，其他地方无法按语言进行筛选，因为目前github api不支持。
我也知道github网页端支持starred repos按语言筛选，但是api中不提供，手机端也无法实现。

**Comment by Vixb1122** [comment]
这跟是否提供api没关系吧。
进入页面请求所有版本库，筛选时候用请求到的数据中的语言字段进行筛选不就可以了。。

**Comment by ThirtyDegreesRay** [comment]
获取所有版本库这种做法是不可取的，数据流量浪费，而且会导致请求时间过长，目前一次性只获取30条数据，如果获取1000条数据，甚至更多，需要多久，需要浪费多少数据流量？
国内访问github的网速还比较慢
