### ISSUE TITLE
md跳转md的能不能拦截了直接在应用中跳转啊

### ISSUE THREAD

**Issue by Vixb1122** [ThirtyDegreesRay/OpenHub#22]
目前md文件中的链接，点击后会吊起外部浏览器

**Comment by ThirtyDegreesRay** [comment]
对于软件内部的链接，比如repository、user、issue、commit等可以识别的都会在软件内打开，以后也会增加对其他链接的识别。

另外，下个版本准备使用Custom tables，假如手机上安装了chrome或Firefox等支持Custom tables的浏览器，不能识别的链接，也不会在外部浏览器打开，而是在软件内部调用chrome等浏览器打开，感觉像是在一个软件里面，其实页面是被chrome打开的。

**Comment by jp311** [comment]
要不再提供个 WebView，用得 MIUI 默认浏览器😂

**Comment by ThirtyDegreesRay** [comment]
你手机上设置的默认浏览器是什么，现在是优先按手机默认设置来选择，其次选择策略是先Chrome、Firefox，然后就选第一个可用的浏览器
