### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by Aoi-hosizora** [ThirtyDegreesRay/OpenHub#285]
开启 cache后，当未加载完当前目录(/a/b)时点返回后，路径上确实是返回了上一级目录(/a)了，但是加载结束后内容任然跳转(/a显示成/a/b的内容)，并且会覆盖cache中上级目录(/a错误)的内容。这时再次点击上级目录(/a)就出错显示成子目录的内容(/a/b)

+ 上级目录
![image](https://user-images.githubusercontent.com/31433480/62409724-3e263700-b60e-11e9-8356-4a77724065d2.png)

+ 出错后的上级目录
![image](https://user-images.githubusercontent.com/31433480/62409727-43838180-b60e-11e9-862d-46b9b5febb6b.png)

**Comment by MCwither** [comment]
下拉刷新一下就好了

**Comment by Aoi-hosizora** [comment]
@MCwither 嗯可以，用了那么久我都忘了有下拉刷新emm
