### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by scolia** [ThirtyDegreesRay/OpenHub#36]
Attempt to invoke virtual method 'java.lang.String com.thirtydegreesray.openhub.mvp.model.User.getLogin()' on a null object reference

**Comment by ThirtyDegreesRay** [comment]
收到错误，重试一次是否能成功登录？

**Comment by scolia** [comment]
不能, 还是一样的错误

**Comment by ThirtyDegreesRay** [comment]
是哪种登录方式报错，OAuth登录和直接在软件里面输入用户名密码登录都试试看

**Comment by scolia** [comment]
ok, 现在没问题了.

**Comment by ThirtyDegreesRay** [comment]
好的，问题原因我还是需要找找
