### ISSUE TITLE
Organization界面 内容显示问题

### ISSUE THREAD

**Issue by pzhlkj6612** [ThirtyDegreesRay/OpenHub#38]
和之前一样，请访问这里查看该问题的详情：[Link](https://github.com/pzhlkj6612/OpenHubIssuesRelated/tree/master/Organization-UI)

**Comment by ThirtyDegreesRay** [comment]
* 1.关于成员数目的统计，star数目，repos数目等，以后会添加上。
* 2.根据github的接口获取的，部分组织是有活动的，比如说JetBrains，至于很多没有显示出活动的组织，这个还要查查看为什么接口中没返回

**Comment by pzhlkj6612** [comment]
关于“活动”的获取，实在是我粗心了，刚查看JetBrains，的确能成功刷出活动。
