### ISSUE TITLE
german date format

### ISSUE THREAD

**Issue by Henry2o1o** [ThirtyDegreesRay/OpenHub#41]
```
const-string v1, "d. MMM yyyy"
or
const-string v2, "dd.MM.yyyy HH:mm"
or
const-string v1, "EEE, dd.MM.yyyy HH:mm:ss \'GMT\'"
```
German date format

dd.MM.yyyy
![grafik](https://user-images.githubusercontent.com/6131799/34916325-cfd16ecc-f936-11e7-8d62-a5b70a23a586.png)
![grafik](https://user-images.githubusercontent.com/6131799/34916909-70049254-f93f-11e7-86ab-3caa007132cd.png)

**Comment by Henry2o1o** [comment]
![grafik](https://user-images.githubusercontent.com/6131799/34916931-aa79b0fe-f93f-11e7-84a2-3857bab02e05.png)

works without problems

**Comment by Henry2o1o** [comment]
![grafik](https://user-images.githubusercontent.com/6131799/34917079-db34c52e-f941-11e7-9d71-89a904b93a1a.png) ![grafik](https://user-images.githubusercontent.com/6131799/34917084-e394ca0c-f941-11e7-8368-c61a0284413a.png)

works without problems

**Comment by ThirtyDegreesRay** [comment]
I will fix the problem of date formate.
About the translations, I will check it.
