### ISSUE TITLE
Repo README-cn.md 小问题

### ISSUE THREAD

**Issue by pzhlkj6612** [ThirtyDegreesRay/OpenHub#46]
# 以下问题均已在[Pull Request #45](https://github.com/ThirtyDegreesRay/OpenHub/pull/45)中修复。

</br>

[Link](https://github.com/ThirtyDegreesRay/OpenHub/blob/b6e78709d6e55343c82ff2863bd312fcd11a6d63/README-cn.md#openhub)

> 一个**开源**的GitHub Android客户端应，快速简洁。

这句话不完整。

</br>

[Link](https://github.com/ThirtyDegreesRay/OpenHub/blob/b6e78709d6e55343c82ff2863bd312fcd11a6d63/README-cn.md#app)

> 支持夜间模式，多重主色调

多重 -> 多种 ？

> 支持英文、简体中文和希伯来语

添加上“德语”

> 自动记录浏览过过的用户和版本库

过过

</br>

[Link](https://github.com/ThirtyDegreesRay/OpenHub/blob/b6e78709d6e55343c82ff2863bd312fcd11a6d63/README-cn.md#%E7%89%88%E6%9C%AC%E5%BA%93)

> 查看用户公公的、星标的项目和活动

公公

</br>

# 以下仅为建议：

[Link](https://github.com/ThirtyDegreesRay/OpenHub/blob/b6e78709d6e55343c82ff2863bd312fcd11a6d63/README-cn.md#%E7%89%88%E6%9C%AC%E5%BA%93)

> 星标、关注和fork版本库

这样貌似不太优雅，不如“shar、watch和fork版本库”？

</br>

> 查看你私有的、公开的、forked和星标的版本库

就并列关系而言，可以改为“查看你私有和公开的、forked和starred的版本库”。

**Comment by ThirtyDegreesRay** [comment]
谢谢修改，你修改后的那些中文说明都是可以的，我粗心了。

对于fork一直没有想到一个很好的中文翻译，所以才那么写的，对于fork的翻译，有没有什么建议？

要说并列关系的话，其实私有的、公开的、forked这三个属于同等级关系，因为展示的时候，它们在一个页面，而starred在另一个页面。这个先这样吧，能说明白就行。

**Comment by pzhlkj6612** [comment]
> 对于fork的翻译，有没有什么建议？

关于fork，在 [GitHub 的 Fork 是什么意思？](https://www.zhihu.com/question/20431718/answer/74250205) ，答主 [李鼎](https://www.zhihu.com/people/oldratlee) 提出可理解为“分叉”。但我考虑的是，GitHub本身是英语界面的，为了不让初学者迷惑，就保持用英文吧；而star、watch这些，有成熟的翻译，也就保持用中文啦。

</br>

> 其实私有的、公开的、forked这三个属于同等级关系

你说得对，我没有结合实际情况进行分析；要不这样：
“查看你所有的版本库，包括公开、私有、fork的，以及星标的”

</br>

另外，由于中英文的表达差异，在这里“forked”表示“已分叉”这种状态，应理解为“fork过/fork了”，所以原句应改为“**forked的**和**星标过**的版本库”；但这样读起来有些奇怪，不如改为“**fork**和**星标**的版本库”，即用“fork”表示“分叉”这一动作。
这样可能更生动一些？

---

综上：
- 用词不变，依然是“fork”“星标”这样中英混合的
- 语序改一改（已被包含于[Pull Request #48](https://github.com/ThirtyDegreesRay/OpenHub/pull/48)）。
