### ISSUE TITLE
News页面语言混乱显示问题

### ISSUE THREAD

**Issue by kinegratii** [ThirtyDegreesRay/OpenHub#49]
如图
![231](https://user-images.githubusercontent.com/9875406/35445120-95fb8ff2-02eb-11e8-9fbc-ed9a46ca36cd.png)

设置里语言为中文，但是在News页面有时会出现中文、英文混乱显示的Bug。

**其他**

- 这种情况只是偶尔出现，特别是连续多次刷新的时候；
- 暂时只在News页面发现这一个问题；

**环境**

- OpenHub:v2.5.0
- Android：7.0

**Comment by pzhlkj6612** [comment]
这里发现一另外的情况：

"Open Pull Request"与"Closed Pull Request"这俩在News和个人的活动里看到的是英文原文，没有翻译。

**Comment by ThirtyDegreesRay** [comment]
@kinegratii 语言混乱，以前是因为webview加载时可能会导致设置的语言无效，在webview页面多设置了一次就可以了。你发现的这个问题，我会想办法找找看原因。

**Comment by ThirtyDegreesRay** [comment]
@pzhlkj6612 这两个的确还没有翻译，当时没想到合适的翻译，后来也就一直没处理，我来添加下翻译。
