### ISSUE TITLE
好像不能切换分支

### ISSUE THREAD

**Issue by Hansi7** [ThirtyDegreesRay/OpenHub#59]
就是我要看除master以外的分支代码，客户端不能切换。

**Comment by pzhlkj6612** [comment]
进repo，右上角菜单按钮旁有切换分支的按钮。

**Comment by pzhlkj6612** [comment]
说起来，这个功能在文档里还没写上呢。 @ThirtyDegreesRay

**Comment by Hansi7** [comment]
可以了，原来如此。看图标我以为是fork别人的意思。我就没试。哈哈。

**Comment by pzhlkj6612** [comment]
嗯哼。另外，你可以去Repo的菜单里 `Fork` 。

**Comment by ThirtyDegreesRay** [comment]
@pzhlkj6612 新年好，放假刚回来，我来在文档中添加下这个功能。

**Comment by pzhlkj6612** [comment]
#107 
这个选择分支的功能，真是太不明显了- -我估计今后还会接到类似的 issue。
