### ISSUE TITLE
Release to the F-Droid.

### ISSUE THREAD

**Issue by jp311** [ThirtyDegreesRay/OpenHub#6]
非常棒的 App！不过考虑到国内市场的尿性，建议发布到 F-Droid

**Comment by moriel5** [comment]
If you are talking about getting OpenHub into F-Droid, I had already pitched the idea to @ThirtyDegreesRay, and he is already thinking about (see here: https://github.com/ThirtyDegreesRay/OpenHub/issues/1).

However it is great that you are also asking for the same cause!

**Comment by ThirtyDegreesRay** [comment]
@jp311 @moriel5 Thanks for your advice, I am preparing.

**Comment by moriel5** [comment]
I'm glad to hear that.

**Comment by ShalokShalom** [comment]
I also think this helps.
