### ISSUE TITLE
关于安卓版本支持问题

### ISSUE THREAD

**Issue by VergeDX** [ThirtyDegreesRay/OpenHub#61]
请问可以增加4.4.4的适配嘛……  
老机子不能用很难受的  
以前的发行版有适配4.4.4的吗？

**Comment by ThirtyDegreesRay** [comment]
不好意思，项目一开始就在5.0的基础上开发的，没有支持4.4.4的版本。
暂时还没有时间适配4.4.4，需要改的东西比较多，还有不少新功能需要开发完善，优先做新功能，如果想在4.4.4上使用github客户端，推荐你使用[OctoDroid](https://github.com/slapperwan/gh4a)，这个也不错。

**Comment by VergeDX** [comment]
谢谢您w
我现在使用的就是OctoDroid，不过有时连不上Github服务器
