### ISSUE TITLE
Pressing on activity should show the details of this activity

### ISSUE THREAD

**Issue by itzikiap** [ThirtyDegreesRay/OpenHub#8]
Hi, when I press an activity, the project page for this activity is loaded. instead, I wish to see the details of the activity.
Thank you

**Comment by ThirtyDegreesRay** [comment]
The display for activities will be improved latter, the list of activities will show more info about activities, and click to show description on new page.

**Comment by itzikiap** [comment]
Thanks

**Comment by ThirtyDegreesRay** [comment]
Thanks for your suggestion too.

**Comment by darkmice** [comment]
最好增加分类浏览，

**Comment by ThirtyDegreesRay** [comment]
@darkmice Thanks for your suggestion, but there are so many types of activities, it's will be not convenient to user.
