### ISSUE TITLE
Commits and Intents

### ISSUE THREAD

**Issue by moriel5** [ThirtyDegreesRay/OpenHub#9]
I had noticed (ironically, after I had uninstalled ForkHub), that OpenHub does not offer any way to view individual commits.

Other than that, I think it would be a good idea to implement an intent for opening GitHub links (currently, I can only open them within the browser).

Writing comments from within OpenHub is definitely comfortable, thanks for that!

**Comment by ThirtyDegreesRay** [comment]
Aha, I was thinking about the design of commit page and the way to open GitHub links on OpenHub at last night,  what a coincidence. And the user of coolapk wanted commits too.

So, see you next version.

Thanks for your supports to OpenHub all the time.

**Comment by moriel5** [comment]
I'm glad to be of help.
By the way, are there any new strings that I can translate?

**Comment by ThirtyDegreesRay** [comment]
Some strings([string.xml](https://github.com/ThirtyDegreesRay/OpenHub/blob/master/app/src/main/res/values-iw/strings.xml#L199)) traslated by google translate, you can translate these.
